### ISSUE TITLE
Add RAPL domain PSYS support when available

### ISSUE THREAD

**Issue by bpetit** [hubblo-org/windows-rapl-driver#7]
RAPL domain PSYS reports power usage at the "platform" / "SoC" level instead of just the CPU package, which is very valuable information we are trying to get in scaphandre when possible.

It is only available since Skylake (and not always present even if skylake),

It is based on [MSR_PLATFORM_ENERGY_STATUS](https://docs.rs/dbs-arch/latest/dbs_arch/msr/constant.MSR_PLATFORM_ENERGY_STATUS.html)

It seems this MSR has to be read differently than the DRAM and PKG ones : https://patchwork.kernel.org/project/linux-pm/patch/20211207131734.2607104-1-rui.zhang@intel.com/

Related to https://github.com/hubblo-org/scaphandre/issues/316

**Comment by Vic063** [comment]
I just tried on an i7-6600U (see specs here: https://www.intel.com/content/www/us/en/products/sku/88192/intel-core-i76600u-processor-4m-cache-up-to-3-40-ghz/specifications.html) which a Skylake family processor.

Sadly, it seems that this CPU doesn't support these MSRs, at least the register MSR_PLATFORM_ENERGY_COUNTER returns 0 on my side.

I will try later on another CPU (Kaby Lake family) to see if the results change.

**Comment by Vic063** [comment]
Tested on an i7-7500U (see specs here: https://www.intel.com/content/www/us/en/products/sku/95451/intel-core-i77500u-processor-4m-cache-up-to-3-50-ghz/specifications.html) which is a Kaby Lake family processor.

It works on this CPU, I wrote a simple Python script (for Linux only) which extract the value of this MSR register.

`import os
import time


def readmsr(cpu_idx, register_index):
    fd = os.open(f'/dev/cpu/{cpu_idx}/msr', os.O_RDONLY)
    os.lseek(fd, register_index, os.SEEK_SET)
    value = os.read(fd, 8)
    os.close(fd)
    return int.from_bytes(value, 'little')


while True:
    for i in range(0, 4):
        rapl_power = readmsr(i, 0x606)
        energy_units = 1. / pow(2, (rapl_power >> 8) & 0x1F)
        time_units = 1. / pow(2, (rapl_power >> 16) & 0x0F)

        energy_counter = readmsr(i, 0x64D)
        if energy_counter == 0:
            print('Unsupported CPU does not have MSR_PLATFORM_ENERGY_COUNTER support')
            exit(1)
        print(f'CPU{i}: {(energy_counter * energy_units) / (time_units * 1000)} Watts')
    time.sleep(1)
    print('-' * 20)`

Be sure to modprobe msr before running the Python script.
